In [2]:
import pandas as pd

In [4]:
raw_df = pd.read_csv("/content/spam_or_not_spam.csv")
df = raw_df.copy()

In [5]:
df.head()

                                                  email  label
2995   abc s good morning america ranks it the NUMBE...      1
2996   hyperlink hyperlink hyperlink let mortgage le...      1
2997   thank you for shopping with us gifts for all ...      1
2998   the famous ebay marketing e course learn to s...      1
2999   hello this is chinese traditional 子 件 NUMBER世...      1

In [6]:
df.tail()

                                                  email  label
2995   abc s good morning america ranks it the NUMBE...      1
2996   hyperlink hyperlink hyperlink let mortgage le...      1
2997   thank you for shopping with us gifts for all ...      1
2998   the famous ebay marketing e course learn to s...      1
2999   hello this is chinese traditional 子 件 NUMBER世...      1

Data Cleaning

In [7]:
print(df.isnull().sum())

email    1
label    0
dtype: int64

In [8]:
df = df.dropna()

In [9]:
df = df.drop_duplicates()

In [10]:
#convert text to lowercase
df['email'] = df['email'].str.lower()

In [13]:
#Tokenisation
import nltk
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize
df['email'] = df['email'].apply(word_tokenize)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [14]:
#remove stopwords
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

df['email'] = df['email'].apply(lambda x: " ".join([word for word in x if word not in stop_words]) )

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [17]:
#Lemmatization
nltk.download('wordnet')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

df['email'] = df['email'].apply(lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))

[nltk_data] Downloading package wordnet to /root/nltk_data...

In [18]:
df

                                                  email  label
0     date wed number aug number number number numbe...      0
1     martin posted tasso papadopoulos greek sculpto...      0
2     man threatens explosion moscow thursday august...      0
3     klez virus die already prolific virus ever kle...      0
4     adding cream spaghetti carbonara effect pasta ...      0
...                                                 ...    ...
2995  abc good morning america rank number christmas...      1
2996  hyperlink hyperlink hyperlink let mortgage len...      1
2997  thank shopping u gift occasion free gift numbe...      1
2998  famous ebay marketing e course learn sell comp...      1
2999  hello chinese traditional 子 件 number世 o最有效的宣 鞣...      1

[2872 rows x 2 columns]

In [21]:
#vectorisation
from numpy import vectorize
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['email'])

In [24]:
y = df['email']

In [25]:
#splitting

from sklearn.model_selection import train_test_split

X_train, y_train, X_test, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [26]:
# Convert sparse matrices to dense NumPy arrays if they are sparse
from scipy.sparse import issparse

if issparse(X_train):
    X_train = X_train.toarray()
if issparse(X_test):
    X_test = X_test.toarray()

Model

In [ ]:
model =